name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'
version: 1.0.0+0
environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.1.0
  provider: ^6.1.5
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  image_picker: ^1.0.7
  share_plus: ^11.0.0
  photo_view: ^0.14.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  path_provider: ^2.1.5
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_svg: ^2.2.0
  country_code_picker: ^3.2.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  flutter_typeahead: ^5.2.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.17.0
  flutter_widget_from_html_core: ^0.17.0
  fluttertoast: ^8.0.9
  permission_handler: ^11.1.0
  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.1.5
  path: ^1.8.3
  cached_network_image: ^3.4.1
  http_parser: ^4.0.2
  intl: ^0.20.2
  sign_in_with_apple: ^6.1.0
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^4.0.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  emoji_picker_flutter: ^3.1.0
  file_picker: 8.1.4
  carousel_slider: 5.1.1
  webview_flutter_android: ^3.13.2
  webview_flutter_wkwebview: ^3.10.1
  dropdown_button2: ^2.3.9
  gradient_borders: ^1.0.0
  flutter_spinkit: ^5.2.1
  open_file: ^3.5.10
  flutter_pdfview: ^1.2.7
  readmore: ^3.0.0
  open_file_manager: ^1.0.2
  audioplayers: ^6.5.0
  syncfusion_flutter_pdfviewer: ^28.2.4
  firebase_auth: ^5.7.0
  flutter_inappwebview_ios: ^1.1.2
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  get_thumbnail_video: ^0.7.3
  archive: ^4.0.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  syncfusion_flutter_datepicker: ^28.2.4
  syncfusion_flutter_core: ^28.2.4
  webview_flutter: ^4.9.0
  skeletonizer: ^1.4.3
  phone_numbers_parser: ^9.0.3


#dependency_overrides:
#  firebase_core_platform_interface: ^5.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/svg/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
